### ISSUE TITLE
ES6 Set support

### ISSUE THREAD

**Issue by murphydanger** [shouldjs/equal#1]
Is it possible to work ES6 set support into this? I would love to be able to compare 2 sets, and see which members differ.

Thanks for the outstanding work, regardless!

**Comment by btd** [comment]
Yep, that is possible. Will try to make it on this week.

**Comment by btd** [comment]
@murphydanger question. I did initial support but not sure about one moment.
If i use Map/Set .has method i cannot check if keys are objects (as it looks it just do === for non primitive). But if i will do iteration by both set/map it will much slower then using .has.

Thoughts?

**Comment by murphydanger** [comment]
How much slower is "much slower?" Maybe you can run a test on a set of 1000 elements?

**Comment by btd** [comment]
I did not measured perfomance actually it is difference in complexity O(N^2) vs O(N) (in perfect case, usual just O(N * log N).
Anyway i decide to use deep comparison, because by principe of less surprise i would expect the same behaviour from all objects.
Anyway i did check if key is primitive it will use .has (and .get for es6 map), and if it is object it will do full equality check using iterators.

**Comment by murphydanger** [comment]
1. O(n^2) vs O(n*log(n)) doesn't bother me for the types of data javascript applications handle -- especially in a test bed.

2. >  i would expect the same behaviour from all objects.

    Exactly.

3. Thanks for this, you rock!
